services:
        group4_user.registration.form.type:
          class: Group4\UserBundle\Form\Type\RegistrationFormType
          arguments: [%fos_user.model.user.class%]
          tags:
            - { name: form.type, alias: group4_user_registration }