<?php

namespace Group4\ChallengeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerToChallengeRepository extends EntityRepository
{
}
