<?php

namespace Group4\ChallengeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends EntityRepository
{

    /**
     * @return ArrayCollection|Theme[]
     */
    public function getApprovedThemes()
    {
        $query = $this->getEntityManager()->createQuery('
            SELECT t FROM Group4\ChallengeBundle\Entity\Theme AS t
             WHERE t.approved = 1
             ORDER BY t.name ASC
         ');

        $themes = $query->getResult();

        return $themes;
    }

}
