services:
    sonata.admin.post:
        class: Group4\ChallengeBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Themes" }
        arguments:
            - ~
            - Group4\ChallengeBundle\Entity\Theme
            - ~
        calls:
            - [ setTranslationDomain, [Group4ChallengeBundle]]