challenge_homepage:
    pattern:  /challenge
    defaults: { _controller: ChallengeBundle:Challenge:index }

challenge_new:
    pattern: /challenge/new
    defaults: { _controller: ChallengeBundle:Challenge:new }

theme_insert_success:
    pattern: /challenge/new/success
    defaults: { _controller: ChallengeBundle:Challenge:newSuccess }

theme_list_all:
    pattern: /challenge/listAll
    defaults: { _controller: ChallengeBundle:Challenge:listAll }
