challenge_homepage:
    pattern:  /challenge
    defaults: { _controller: ChallengeBundle:Challenge:index }

challenge_admin:
    pattern: /challenge/admin
    defaults: { _controller: ChallengeBundle:Challenge:admin }

player_photo_upload:
    pattern: /challenge/upload
    defaults: { _controller: ChallengeBundle:Player:upload }

participate:
    pattern: /challenge/participate/{type}
    defaults: { _controller: ChallengeBundle:Player:joinChallenge }

vote:
    defaults: { _controller: ChallengeBundle:Player:vote }
    pattern: /challenge/vote/{playerToChallengeId}

show_challenge:
    defaults: { _controller: ChallengeBundle:Player:showChallenge }
    pattern: /show/{eventId}

show_challenge_with_focus:
    defaults: { _controller: ChallengeBundle:Player:showChallenge }
    pattern: /show/{eventId}/{userId}

